# Generated by Django 2.2.5 on 2019-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_active', models.BooleanField(default=False, verbose_name='Indique si les votes sont actifs')),
                ('_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début des votes')),
                ('_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin des votes')),
            ],
        ),
    ]
